/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8yhBRaKsBf3R2wKMhT5dUU
// Component: B0YwF5yls5yO
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import TsfDemandMainNavigation from "../../TsfDemandMainNavigation"; // plasmic-import: RS9jruOWtFtt/component
import { BaseButton } from "@plasmicpkgs/react-aria/skinny/registerButton";
import TsfFooter from "../../TsfFooter"; // plasmic-import: NmgYw5lHKANx/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 8yhBRaKsBf3R2wKMhT5dUU/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 8yhBRaKsBf3R2wKMhT5dUU/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 8yhBRaKsBf3R2wKMhT5dUU/projectcss
import sty from "./PlasmicCaseStudies.module.css"; // plasmic-import: B0YwF5yls5yO/css
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: iCnGomX0kBnc/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: psfpTc-XGOO7/icon
import ArrowRightSvgIcon from "./icons/PlasmicIcon__ArrowRightSvg"; // plasmic-import: WXIx2uHDhf9R/icon

createPlasmicElementProxy;

export const PlasmicCaseStudies__VariantProps = new Array();

export const PlasmicCaseStudies__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCaseStudies__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__mDhU8)}>
            <div className={classNames(projectcss.all, sty.freeBox__nT3Lu)}>
              <TsfDemandMainNavigation
                data-plasmic-name={"tsfDemandMainNavigation"}
                data-plasmic-override={overrides.tsfDemandMainNavigation}
                className={classNames(
                  "__wab_instance",
                  sty.tsfDemandMainNavigation
                )}
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__aubmX)}>
              <div className={classNames(projectcss.all, sty.freeBox__bO4Om)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___0AuEg)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__suwQy)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ypwXv)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Ready to accept or acquiesce willing."
                          : "Hero for your SaaS landing page."}
                      </h1>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__t0NoZ
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut ."
                        }
                      </div>
                      <BaseButton
                        className={classNames(
                          "__wab_instance",
                          sty.ariaButton__wvxi5
                        )}
                        target={$props.openLinkInNewTab ? "_blank" : "_self"}
                      >
                        {false ? (
                          <div
                            data-plasmic-name={"softBackground3"}
                            data-plasmic-override={overrides.softBackground3}
                            className={classNames(
                              projectcss.all,
                              sty.softBackground3
                            )}
                          />
                        ) : null}
                        {false ? (
                          <div
                            data-plasmic-name={"border3"}
                            data-plasmic-override={overrides.border3}
                            className={classNames(projectcss.all, sty.border3)}
                          />
                        ) : null}
                        <div
                          data-plasmic-name={"interactionEffect3"}
                          data-plasmic-override={overrides.interactionEffect3}
                          className={classNames(
                            projectcss.all,
                            sty.interactionEffect3
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___5M2Ha
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__pur3M
                            )}
                          >
                            <CircleIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___8WXDa
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uuqgH
                            )}
                          >
                            {"Get started"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__a44XX
                            )}
                          >
                            <ChevronDownIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__j3Ux3
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </BaseButton>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__naLnQ)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ctuHf)}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <section
            data-plasmic-name={"features"}
            data-plasmic-override={overrides.features}
            className={classNames(projectcss.all, sty.features)}
          >
            <div className={classNames(projectcss.all, sty.column__ldW5O)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__h4FzN
                )}
              >
                {"Value propositions headline."}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rRCcv
                )}
              >
                {
                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                }
              </div>
              <div
                data-plasmic-name={"container4"}
                data-plasmic-override={overrides.container4}
                className={classNames(projectcss.all, sty.container4)}
              >
                <div
                  data-plasmic-name={"outerRow2"}
                  data-plasmic-override={overrides.outerRow2}
                  className={classNames(projectcss.all, sty.outerRow2)}
                >
                  <div
                    data-plasmic-name={"row2"}
                    data-plasmic-override={overrides.row2}
                    className={classNames(projectcss.all, sty.row2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__knq28)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___73Y86
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__f3EPe
                          )}
                        />

                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__yLxTp
                          )}
                        >
                          {"Some value proposition of your service."}
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3W8Hu
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                          }
                        </div>
                        <BaseButton
                          className={classNames(
                            "__wab_instance",
                            sty.ariaButton___85SyA
                          )}
                          target={$props.openLinkInNewTab ? "_blank" : "_self"}
                        >
                          {false ? (
                            <div
                              data-plasmic-name={"softBackground4"}
                              data-plasmic-override={overrides.softBackground4}
                              className={classNames(
                                projectcss.all,
                                sty.softBackground4
                              )}
                            />
                          ) : null}
                          {false ? (
                            <div
                              data-plasmic-name={"border4"}
                              data-plasmic-override={overrides.border4}
                              className={classNames(
                                projectcss.all,
                                sty.border4
                              )}
                            />
                          ) : null}
                          <div
                            data-plasmic-name={"interactionEffect4"}
                            data-plasmic-override={overrides.interactionEffect4}
                            className={classNames(
                              projectcss.all,
                              sty.interactionEffect4
                            )}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__fgOFl
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__wo4ME
                              )}
                            >
                              <CircleIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__xvjT
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hnjVf
                              )}
                            >
                              {"Learn more"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__bj0Fb
                              )}
                            >
                              <ArrowRightSvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___31Zr7
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </BaseButton>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__a8MJw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__t3GXn
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__eil0C)}
                          displayHeight={"400px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"400px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/tsf_demand_website/images/corinneKutzTMi2R5NfoUnsplashJpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"container5"}
                data-plasmic-override={overrides.container5}
                className={classNames(projectcss.all, sty.container5)}
              >
                <div
                  data-plasmic-name={"outerRow3"}
                  data-plasmic-override={overrides.outerRow3}
                  className={classNames(projectcss.all, sty.outerRow3)}
                >
                  <div
                    data-plasmic-name={"row4"}
                    data-plasmic-override={overrides.row4}
                    className={classNames(projectcss.all, sty.row4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__xINv)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__l6PpR)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"400px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tsf_demand_website/images/tiffanyTertipesNxcs8Wwj9J0UnsplashJpg.jpg",
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__jP8Q)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kdmnX
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cEmEi
                          )}
                        />

                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___7Dni7
                          )}
                        >
                          {"Some value proposition of your service."}
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9FvYz
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                          }
                        </div>
                        <BaseButton
                          className={classNames(
                            "__wab_instance",
                            sty.ariaButton__gDik
                          )}
                          target={$props.openLinkInNewTab ? "_blank" : "_self"}
                        >
                          {false ? (
                            <div
                              data-plasmic-name={"softBackground5"}
                              data-plasmic-override={overrides.softBackground5}
                              className={classNames(
                                projectcss.all,
                                sty.softBackground5
                              )}
                            />
                          ) : null}
                          {false ? (
                            <div
                              data-plasmic-name={"border5"}
                              data-plasmic-override={overrides.border5}
                              className={classNames(
                                projectcss.all,
                                sty.border5
                              )}
                            />
                          ) : null}
                          <div
                            data-plasmic-name={"interactionEffect5"}
                            data-plasmic-override={overrides.interactionEffect5}
                            className={classNames(
                              projectcss.all,
                              sty.interactionEffect5
                            )}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___1Vd8I
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__jly5J
                              )}
                            >
                              <CircleIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__bf1J4
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xp6Pj
                              )}
                            >
                              {"Learn more"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__cpih9
                              )}
                            >
                              <ArrowRightSvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__l2NMn
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </BaseButton>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"container6"}
                data-plasmic-override={overrides.container6}
                className={classNames(projectcss.all, sty.container6)}
              >
                <div
                  data-plasmic-name={"outerRow4"}
                  data-plasmic-override={overrides.outerRow4}
                  className={classNames(projectcss.all, sty.outerRow4)}
                >
                  <div
                    data-plasmic-name={"row3"}
                    data-plasmic-override={overrides.row3}
                    className={classNames(projectcss.all, sty.row3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__kU8B8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___8Xvom
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__d4Rw
                          )}
                        />

                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__c54P
                          )}
                        >
                          {"Some value proposition of your service."}
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__alVh0
                          )}
                        >
                          {
                            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                          }
                        </div>
                        <BaseButton
                          className={classNames(
                            "__wab_instance",
                            sty.ariaButton__yw8R8
                          )}
                          target={$props.openLinkInNewTab ? "_blank" : "_self"}
                        >
                          {false ? (
                            <div
                              data-plasmic-name={"softBackground6"}
                              data-plasmic-override={overrides.softBackground6}
                              className={classNames(
                                projectcss.all,
                                sty.softBackground6
                              )}
                            />
                          ) : null}
                          {false ? (
                            <div
                              data-plasmic-name={"border6"}
                              data-plasmic-override={overrides.border6}
                              className={classNames(
                                projectcss.all,
                                sty.border6
                              )}
                            />
                          ) : null}
                          <div
                            data-plasmic-name={"interactionEffect6"}
                            data-plasmic-override={overrides.interactionEffect6}
                            className={classNames(
                              projectcss.all,
                              sty.interactionEffect6
                            )}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__pe7Nv
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__kCYq
                              )}
                            >
                              <CircleIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__fg4Sq
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lbht6
                              )}
                            >
                              {"Learn more"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__fSiqe
                              )}
                            >
                              <ArrowRightSvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ybJe5
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                        </BaseButton>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__bpOGq)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qr7Jj)}
                        displayHeight={"400px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"400px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tsf_demand_website/images/xpsOcAuPlfZxEcUnsplashJpg.jpg",
                          fullWidth: 640,
                          fullHeight: 360,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            <div className={classNames(projectcss.all, sty.column__kn0L1)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__kJmUd
                )}
              >
                {"Testimonials"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dAavP
                )}
              >
                {
                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                }
              </div>
              <div className={classNames(projectcss.all, sty.columns__kEkFb)}>
                <div className={classNames(projectcss.all, sty.column__mmYV)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__uWlOn)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__gkf2C)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__wTz3N
                        )}
                      >
                        {"\u201c"}
                      </h2>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6E4P
                        )}
                      >
                        {
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__zk5Ob
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___4WUqH
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__y9K5D)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/tsf_demand_website/images/smallJpg.jpg",
                              fullWidth: 160,
                              fullHeight: 160,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___7Mowq
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__hQ0MW
                            )}
                          >
                            {"Lorem Ipsum"}
                          </h5>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___2P8Dn)}>
                  <div
                    className={classNames(projectcss.all, sty.columns___4Ndr5)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__a6HKd)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___3H9PS)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tsf_demand_website/images/mePng.png",
                          fullWidth: 140,
                          fullHeight: 140,
                          aspectRatio: undefined
                        }}
                      />

                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__djXnn
                        )}
                      >
                        {"Zulia Maron Duo"}
                      </h5>
                      <div
                        before={""}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vAHcG
                        )}
                      >
                        {
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                        }
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__cmHbf)}>
                  <div
                    className={classNames(projectcss.all, sty.columns__jNru)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__j4C3U)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__qcodq
                        )}
                      >
                        {"\u201c"}
                      </h2>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w7Jwa
                        )}
                      >
                        {
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns___8GDcv
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__vMjpa
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__xGkwn)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/tsf_demand_website/images/thumbAvatar1583758683Jpg.jpg",
                              fullWidth: 160,
                              fullHeight: 160,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__nRx6P
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5___0DLGt
                            )}
                          >
                            {"Lorem Ipsum"}
                          </h5>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.columns__wop6X)}>
            <div className={classNames(projectcss.all, sty.column__mYbK)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__a74NE
                )}
              >
                {"Blog"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__akIbN
                )}
              >
                {
                  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                }
              </div>
              <div className={classNames(projectcss.all, sty.columns__ekCOf)}>
                <div className={classNames(projectcss.all, sty.column__vyhCz)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5Zhuj)}
                    displayHeight={"230px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tsf_demand_website/images/fakurianDesignPPTwRTkvXqUnsplashJpg.jpg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.columns__igm4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__kZloz)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7E5Bn
                        )}
                      >
                        {"January 03, 2021"}
                      </div>
                      <h4
                        className={classNames(
                          projectcss.all,
                          projectcss.h4,
                          projectcss.__wab_text,
                          sty.h4__gpOC
                        )}
                      >
                        {"Convincing reasons you need to learn"}
                      </h4>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___13Hk2
                        )}
                      >
                        {
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                        }
                      </div>
                      <BaseButton
                        className={classNames(
                          "__wab_instance",
                          sty.ariaButton__edV8L
                        )}
                        target={$props.openLinkInNewTab ? "_blank" : "_self"}
                      >
                        <div
                          data-plasmic-name={"softBackground7"}
                          data-plasmic-override={overrides.softBackground7}
                          className={classNames(
                            projectcss.all,
                            sty.softBackground7
                          )}
                        />

                        {false ? (
                          <div
                            data-plasmic-name={"border7"}
                            data-plasmic-override={overrides.border7}
                            className={classNames(projectcss.all, sty.border7)}
                          />
                        ) : null}
                        <div
                          data-plasmic-name={"interactionEffect7"}
                          data-plasmic-override={overrides.interactionEffect7}
                          className={classNames(
                            projectcss.all,
                            sty.interactionEffect7
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lck3K
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__b6Ok6
                            )}
                          >
                            <CircleIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xjbUg
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jByva
                            )}
                          >
                            {"Read more"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__kqbIj
                            )}
                          >
                            <ChevronDownIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__jAwMs
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </BaseButton>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___3Y5R)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__y1QNh)}
                    displayHeight={"230px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tsf_demand_website/images/fakurianDesignLfbhDph3QYUnsplashJpg.jpg",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.columns__kzjI3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___5AD0Q)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w5EIo
                        )}
                      >
                        {"January 03, 2021"}
                      </div>
                      <h4
                        className={classNames(
                          projectcss.all,
                          projectcss.h4,
                          projectcss.__wab_text,
                          sty.h4__dZuXu
                        )}
                      >
                        {"The five devices you need to work anytime"}
                      </h4>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9ZroG
                        )}
                      >
                        {
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                        }
                      </div>
                      <BaseButton
                        className={classNames(
                          "__wab_instance",
                          sty.ariaButton__adGmA
                        )}
                        target={$props.openLinkInNewTab ? "_blank" : "_self"}
                      >
                        <div
                          data-plasmic-name={"softBackground8"}
                          data-plasmic-override={overrides.softBackground8}
                          className={classNames(
                            projectcss.all,
                            sty.softBackground8
                          )}
                        />

                        {false ? (
                          <div
                            data-plasmic-name={"border8"}
                            data-plasmic-override={overrides.border8}
                            className={classNames(projectcss.all, sty.border8)}
                          />
                        ) : null}
                        <div
                          data-plasmic-name={"interactionEffect8"}
                          data-plasmic-override={overrides.interactionEffect8}
                          className={classNames(
                            projectcss.all,
                            sty.interactionEffect8
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sSrur
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__sD4TS
                            )}
                          >
                            <CircleIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__v8VqT
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tx4Qm
                            )}
                          >
                            {"Read more"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__wZgN
                            )}
                          >
                            <ChevronDownIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__dfTzQ
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </BaseButton>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__fBa1U)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5CPIb)}
                    displayHeight={"230px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tsf_demand_website/images/blog2390X290Jpg.jpg",
                      fullWidth: 390,
                      fullHeight: 290,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.columns__ohw2Q)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__lvk92)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xvaf0
                        )}
                      >
                        {"January 03, 2021"}
                      </div>
                      <h4
                        className={classNames(
                          projectcss.all,
                          projectcss.h4,
                          projectcss.__wab_text,
                          sty.h4__kywbU
                        )}
                      >
                        {"Tiktok Illegally collecting data sharing"}
                      </h4>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ombbw
                        )}
                      >
                        {
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                        }
                      </div>
                      <BaseButton
                        className={classNames(
                          "__wab_instance",
                          sty.ariaButton___7FUwr
                        )}
                        target={$props.openLinkInNewTab ? "_blank" : "_self"}
                      >
                        <div
                          data-plasmic-name={"softBackground9"}
                          data-plasmic-override={overrides.softBackground9}
                          className={classNames(
                            projectcss.all,
                            sty.softBackground9
                          )}
                        />

                        {false ? (
                          <div
                            data-plasmic-name={"border9"}
                            data-plasmic-override={overrides.border9}
                            className={classNames(projectcss.all, sty.border9)}
                          />
                        ) : null}
                        <div
                          data-plasmic-name={"interactionEffect9"}
                          data-plasmic-override={overrides.interactionEffect9}
                          className={classNames(
                            projectcss.all,
                            sty.interactionEffect9
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___8ZU2F
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__quJe
                            )}
                          >
                            <CircleIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__o9ABt
                              )}
                              role={"img"}
                            />
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xkdoe
                            )}
                          >
                            {"Read more"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__herH0
                            )}
                          >
                            <ChevronDownIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__puaG
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </BaseButton>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.columns__zqSBi)}>
            <div
              data-plasmic-name={"outer"}
              data-plasmic-override={overrides.outer}
              className={classNames(projectcss.all, sty.outer)}
            >
              <div
                data-plasmic-name={"container3"}
                data-plasmic-override={overrides.container3}
                className={classNames(projectcss.all, sty.container3)}
              >
                <div className={classNames(projectcss.all, sty.column___2BETb)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__u1Cvk
                    )}
                  >
                    {"Want more information?"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5Md91
                    )}
                  >
                    {"Lorem ipsum dolor sit amet, consectetur adipiscing elit."}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___5NrSh)}>
                  <BaseButton
                    className={classNames(
                      "__wab_instance",
                      sty.ariaButton__qvEbW
                    )}
                    target={$props.openLinkInNewTab ? "_blank" : "_self"}
                  >
                    {false ? (
                      <div
                        data-plasmic-name={"softBackground10"}
                        data-plasmic-override={overrides.softBackground10}
                        className={classNames(
                          projectcss.all,
                          sty.softBackground10
                        )}
                      />
                    ) : null}
                    {false ? (
                      <div
                        data-plasmic-name={"border10"}
                        data-plasmic-override={overrides.border10}
                        className={classNames(projectcss.all, sty.border10)}
                      />
                    ) : null}
                    <div
                      data-plasmic-name={"interactionEffect10"}
                      data-plasmic-override={overrides.interactionEffect10}
                      className={classNames(
                        projectcss.all,
                        sty.interactionEffect10
                      )}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__djNn)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jUkPt
                        )}
                      >
                        <CircleIcon
                          className={classNames(projectcss.all, sty.svg__heYXm)}
                          role={"img"}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tiLa0
                        )}
                      >
                        {"Contact us"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sJbj2
                        )}
                      >
                        <ArrowRightSvgIcon
                          className={classNames(projectcss.all, sty.svg__fdizt)}
                          role={"img"}
                        />
                      </div>
                    </div>
                  </BaseButton>
                </div>
              </div>
            </div>
          </section>
          <div className={classNames(projectcss.all, sty.freeBox___9HIy)}>
            <div className={classNames(projectcss.all, sty.columns__n78W8)}>
              <div className={classNames(projectcss.all, sty.column__m5Ugr)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__weXn1
                  )}
                >
                  {"Make your call to action here."}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nOIc
                  )}
                >
                  {"Lorem ipsum dolor sit amet, consectetur adipiscing elit."}
                </div>
                <BaseButton
                  className={classNames(
                    "__wab_instance",
                    sty.ariaButton__tf8Jj
                  )}
                  target={$props.openLinkInNewTab ? "_blank" : "_self"}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"softBackground"}
                      data-plasmic-override={overrides.softBackground}
                      className={classNames(projectcss.all, sty.softBackground)}
                    />
                  ) : null}
                  {false ? (
                    <div
                      data-plasmic-name={"border"}
                      data-plasmic-override={overrides.border}
                      className={classNames(projectcss.all, sty.border)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"interactionEffect"}
                    data-plasmic-override={overrides.interactionEffect}
                    className={classNames(
                      projectcss.all,
                      sty.interactionEffect
                    )}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__t445P)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vkf7C)}
                    >
                      <CircleIcon
                        className={classNames(projectcss.all, sty.svg__cz3C5)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__u0Gdf
                      )}
                    >
                      {"Start Now"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__s9Xrj)}
                    >
                      <ChevronDownIcon
                        className={classNames(projectcss.all, sty.svg__fhmM3)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </BaseButton>
              </div>
            </div>
          </div>
          <TsfFooter
            data-plasmic-name={"tsfFooter"}
            data-plasmic-override={overrides.tsfFooter}
            className={classNames("__wab_instance", sty.tsfFooter)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "tsfDemandMainNavigation",
    "h1",
    "softBackground3",
    "border3",
    "interactionEffect3",
    "features",
    "container4",
    "outerRow2",
    "row2",
    "softBackground4",
    "border4",
    "interactionEffect4",
    "container5",
    "outerRow3",
    "row4",
    "softBackground5",
    "border5",
    "interactionEffect5",
    "container6",
    "outerRow4",
    "row3",
    "softBackground6",
    "border6",
    "interactionEffect6",
    "testimonials",
    "softBackground7",
    "border7",
    "interactionEffect7",
    "softBackground8",
    "border8",
    "interactionEffect8",
    "softBackground9",
    "border9",
    "interactionEffect9",
    "outer",
    "container3",
    "softBackground10",
    "border10",
    "interactionEffect10",
    "softBackground",
    "border",
    "interactionEffect",
    "tsfFooter"
  ],

  tsfDemandMainNavigation: ["tsfDemandMainNavigation"],
  h1: ["h1"],
  softBackground3: ["softBackground3"],
  border3: ["border3"],
  interactionEffect3: ["interactionEffect3"],
  features: [
    "features",
    "container4",
    "outerRow2",
    "row2",
    "softBackground4",
    "border4",
    "interactionEffect4",
    "container5",
    "outerRow3",
    "row4",
    "softBackground5",
    "border5",
    "interactionEffect5",
    "container6",
    "outerRow4",
    "row3",
    "softBackground6",
    "border6",
    "interactionEffect6"
  ],

  container4: [
    "container4",
    "outerRow2",
    "row2",
    "softBackground4",
    "border4",
    "interactionEffect4"
  ],

  outerRow2: [
    "outerRow2",
    "row2",
    "softBackground4",
    "border4",
    "interactionEffect4"
  ],

  row2: ["row2", "softBackground4", "border4", "interactionEffect4"],
  softBackground4: ["softBackground4"],
  border4: ["border4"],
  interactionEffect4: ["interactionEffect4"],
  container5: [
    "container5",
    "outerRow3",
    "row4",
    "softBackground5",
    "border5",
    "interactionEffect5"
  ],

  outerRow3: [
    "outerRow3",
    "row4",
    "softBackground5",
    "border5",
    "interactionEffect5"
  ],

  row4: ["row4", "softBackground5", "border5", "interactionEffect5"],
  softBackground5: ["softBackground5"],
  border5: ["border5"],
  interactionEffect5: ["interactionEffect5"],
  container6: [
    "container6",
    "outerRow4",
    "row3",
    "softBackground6",
    "border6",
    "interactionEffect6"
  ],

  outerRow4: [
    "outerRow4",
    "row3",
    "softBackground6",
    "border6",
    "interactionEffect6"
  ],

  row3: ["row3", "softBackground6", "border6", "interactionEffect6"],
  softBackground6: ["softBackground6"],
  border6: ["border6"],
  interactionEffect6: ["interactionEffect6"],
  testimonials: ["testimonials"],
  softBackground7: ["softBackground7"],
  border7: ["border7"],
  interactionEffect7: ["interactionEffect7"],
  softBackground8: ["softBackground8"],
  border8: ["border8"],
  interactionEffect8: ["interactionEffect8"],
  softBackground9: ["softBackground9"],
  border9: ["border9"],
  interactionEffect9: ["interactionEffect9"],
  outer: [
    "outer",
    "container3",
    "softBackground10",
    "border10",
    "interactionEffect10"
  ],

  container3: [
    "container3",
    "softBackground10",
    "border10",
    "interactionEffect10"
  ],

  softBackground10: ["softBackground10"],
  border10: ["border10"],
  interactionEffect10: ["interactionEffect10"],
  softBackground: ["softBackground"],
  border: ["border"],
  interactionEffect: ["interactionEffect"],
  tsfFooter: ["tsfFooter"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCaseStudies__ArgProps,
          internalVariantPropNames: PlasmicCaseStudies__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCaseStudies__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCaseStudies";
  } else {
    func.displayName = `PlasmicCaseStudies.${nodeName}`;
  }
  return func;
}

export const PlasmicCaseStudies = Object.assign(
  // Top-level PlasmicCaseStudies renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tsfDemandMainNavigation: makeNodeComponent("tsfDemandMainNavigation"),
    h1: makeNodeComponent("h1"),
    softBackground3: makeNodeComponent("softBackground3"),
    border3: makeNodeComponent("border3"),
    interactionEffect3: makeNodeComponent("interactionEffect3"),
    features: makeNodeComponent("features"),
    container4: makeNodeComponent("container4"),
    outerRow2: makeNodeComponent("outerRow2"),
    row2: makeNodeComponent("row2"),
    softBackground4: makeNodeComponent("softBackground4"),
    border4: makeNodeComponent("border4"),
    interactionEffect4: makeNodeComponent("interactionEffect4"),
    container5: makeNodeComponent("container5"),
    outerRow3: makeNodeComponent("outerRow3"),
    row4: makeNodeComponent("row4"),
    softBackground5: makeNodeComponent("softBackground5"),
    border5: makeNodeComponent("border5"),
    interactionEffect5: makeNodeComponent("interactionEffect5"),
    container6: makeNodeComponent("container6"),
    outerRow4: makeNodeComponent("outerRow4"),
    row3: makeNodeComponent("row3"),
    softBackground6: makeNodeComponent("softBackground6"),
    border6: makeNodeComponent("border6"),
    interactionEffect6: makeNodeComponent("interactionEffect6"),
    testimonials: makeNodeComponent("testimonials"),
    softBackground7: makeNodeComponent("softBackground7"),
    border7: makeNodeComponent("border7"),
    interactionEffect7: makeNodeComponent("interactionEffect7"),
    softBackground8: makeNodeComponent("softBackground8"),
    border8: makeNodeComponent("border8"),
    interactionEffect8: makeNodeComponent("interactionEffect8"),
    softBackground9: makeNodeComponent("softBackground9"),
    border9: makeNodeComponent("border9"),
    interactionEffect9: makeNodeComponent("interactionEffect9"),
    outer: makeNodeComponent("outer"),
    container3: makeNodeComponent("container3"),
    softBackground10: makeNodeComponent("softBackground10"),
    border10: makeNodeComponent("border10"),
    interactionEffect10: makeNodeComponent("interactionEffect10"),
    softBackground: makeNodeComponent("softBackground"),
    border: makeNodeComponent("border"),
    interactionEffect: makeNodeComponent("interactionEffect"),
    tsfFooter: makeNodeComponent("tsfFooter"),
    // Metadata about props expected for PlasmicCaseStudies
    internalVariantProps: PlasmicCaseStudies__VariantProps,
    internalArgProps: PlasmicCaseStudies__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCaseStudies;
/* prettier-ignore-end */
