/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: o2dUnhjGJYmU8orBU3WQqQ
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantssV4Txcd3FbEr } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: sV4txcd3FBEr/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantssV4Txcd3FbEr
});
